[tool.poetry]
name = "synalinks-server"
version = "0.0.1"
description = ""
authors = ["SynaLinks"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
